### ISSUE TITLE
Customizing Agency Units

### ISSUE THREAD

**Issue by Playmice** [Roomify/agency_units#1]
Hello. I would love to use the agency distribution to build a website where people book event halls. As a result of this, features such as single bedroom, bathrooms and double bedrooms would be irrelevant. Is there a way I can remove those from this module? I am new to drupal

**Comment by istos** [comment]
Those are fields on the bookable units so you can remove them by modifying the entity under admin/rooms/units/unit-types/manage/listing/fields - thanks. Ronald

**Comment by Playmice** [comment]
Alright, thanks.

**Comment by Playmice** [comment]
How do I configure the home page search? I want to add labels and change the placeholders.

**Comment by Playmice** [comment]
Also, on admin/rooms/config/bookings, I can change the guest size displayed on the home page search. However, the maximum value displayed is 20. How do I increase it?
![image](https://cloud.githubusercontent.com/assets/11166933/10540602/56027e86-7401-11e5-8311-c67219d2185c.png)
