### ISSUE TITLE
Configuring home page search

### ISSUE THREAD

**Issue by Playmice** [Roomify/agency_units#2]
How do I configure the home page search? I want to add labels and change the placeholders.
I also want to add fields like Property type

Also, on admin/rooms/config/bookings, I can change the guest size displayed on the home page search. However, the maximum value displayed is 20. How do I increase it?
![image](https://cloud.githubusercontent.com/assets/11166933/10540602/56027e86-7401-11e5-8311-c67219d2185c.png)

**Comment by istos** [comment]
Hi - for both of these issues you are going to need some coding skills. So best move is to take a step back and learn some basic Drupal development skills - visit drupalize.me for some good starting points.
